/*
 * ConfDialog.java
 *
 * Created on 16 wrzesieñ 2003, 22:57
 */

package GUIPack;

import javax.swing.*;
import javax.swing.filechooser.*;
import java.io.*;

/**
 * This bean is to configure out program
 * @author  Damian Dragowski
 */
public class ConfDialog extends javax.swing.JDialog {
    
    /** Holds value of property portNumber. */
    private int portNumber;
    
    /** Holds value of property directory. */
    private String directory;
    
    private final JFileChooser fc = new JFileChooser();    
    
    /** Creates new form ConfDialog */
    public ConfDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setSize(300,270);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(null);

        jTextField1.setText("4422");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jPanel1.add(jTextField1);
        jTextField1.setBounds(160, 30, 50, 20);

        jLabel1.setText("Port pracy serwera:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 30, 130, 16);

        jTextField2.setEditable(false);
        jTextField2.setText("C:\\");
            jPanel1.add(jTextField2);
            jTextField2.setBounds(20, 120, 140, 20);

            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
            jLabel2.setText("\u015acieszka katalogu do kt\u00f3rego bed\u0105");
            jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
            jLabel2.setAutoscrolls(true);
            jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
            jPanel1.add(jLabel2);
            jLabel2.setBounds(20, 70, 210, 20);

            jLabel3.setText("zapisywane pliki sciagni\u0119te");
            jPanel1.add(jLabel3);
            jLabel3.setBounds(20, 90, 200, 16);

            jButton1.setText("Zatwierd\u017a");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            jPanel1.add(jButton1);
            jButton1.setBounds(60, 160, 120, 26);

            jButton2.setText("Wybierz");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });

            jPanel1.add(jButton2);
            jButton2.setBounds(170, 120, 90, 20);

            getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

            pack();
        }//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // Add your handling code here:
        change = true;
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            //This is where a real application would open the file.
            setDirectory(file.getAbsolutePath());
        } else {
            setDirectory("C:\\");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        if ( change )
        {
            System.out.println("Tu cos");
            try
            {
                setPortNumber(Integer.parseInt(jTextField1.getText()));
            }
            catch ( NumberFormatException e )
            {
                setPortNumber(4422);
            }
        }
        ((MainFrame)getParent()).getLog().append("Nale¿y zrestatowaæ aplikacje");
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
    }//GEN-LAST:event_closeDialog

    /** Getter for property portNumber.
     * @return Value of property portNumber.
     *
     */
    public int getPortNumber() {
        return this.portNumber;
    }    
    
    /** Setter for property portNumber.
     * @param portNumber New value of property portNumber.
     *
     */
    public void setPortNumber(int portNumber) {
        this.portNumber = portNumber;
    }    
    
    /** Getter for property directory.
     * @return Value of property directory.
     *
     */
    public String getDirectory() {
        return this.directory;
    }
    
    /** Setter for property directory.
     * @param directory New value of property directory.
     *
     */
    public void setDirectory(String directory) {
        jTextField1.setText("" + portNumber);
        jTextField2.setText(directory);
        this.directory = directory;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private boolean change = true;    
    
}
